### ISSUE TITLE
MIlestone 2 Feedback

### ISSUE THREAD

**Issue by ahofmann4** [UBC-MDS/532_Group_22#66]
HI team 22,

- I found your reflection document very easy to read and was organized in a way that made it very easy to understand what you have and haven’t deployed, why or why not, etc. Thank you!
- Overall, well done getting most of your components working! The dashboard is clean, and not too cluttered.
- In regards to your question about manually cleaning the y-axis of your Tab 1 bar graph, removing the [number] from each label would be more than enough. I don’t think you have to also abbreviate the provinces, not that I think this would actually be too hard with a set of replace commands. I would instead focus on ordering the data in the bar graph, either from highest to lowest or by province. The current order doesn’t make sense and I think is limiting the amount of useful information that someone can get from looking at it. Having the x-axis at the bottom of the graph outside the immediate view is not ideal. Consider putting it at the top of the graph as well, and even more ideal would be for it to float as you scroll. Since region is not a selection on Tab 1 you could even break the bar chart into multiple plots, one for each region, and then order each from highest to lowest.
- For tab 2: As I was using this tab, I found it a little frustrating that my location selection was lost when I toggled between the Province and CMA options. - Thank you for defining CMA in your reflection for me! Otherwise, well done on this tab, the selections work, and the graphs are well done.  
- Nice touch adding a graph save option. It would be helpful if you made a note to let the user know they can do this. It was hard to notice.

**Comment by sbabicki** [comment]
Thanks for your feedback @ahofmann4 ! 

We have made the following updates for Milestone 4 in order to address your feedback:

- Removed the [number] from the labels
- Ordering the bar graph from highest to lowest
- Hight of CMA plot changed so x-axis always showing, no need to scroll
- Highlighting based on province on hover (based on our discussion in lab during the week)
- Better default selections for CMA and Provinces as alternative to saving user selections

We will include the information on these implemented features in our Reflection as well. The suggestions to inform the user of the save option on the site was not implemented, but we will talk about the reason why in the reflection.
